[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
remed = "62GhTM7Hj1Bb5dfWFrxJMwv5LHBqZDhwtNFR17f7F6PB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/jianwei/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
