[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
remed = "Dkmv6cMkyd7riJv6LSqvwDbdsNLNpfEsBwG7X1kZQ2Qz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/jianwei/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
